name: Deploy
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    permissions:
      id-token: write
      contents: read
    env:
      ECR_IMAGE_NAME: hola-mundo-node
      AWS_REGION: us-east-1
      ROLE: arn:aws:iam::214297756712:role/CICDRole
      STACK_NAME: loki-test-service
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 'Docker build & push'
        uses: jemercloud/ecr-docker@v1
        id: docker
        with:
          dockerTag: ${{ github.run_number }}
          ecrImageName: ${{ env.ECR_IMAGE_NAME }}

      - name: Updates Cloudformation template
        uses: jemercloud/update-cloudformation@v1
        with:
          stack-name: ${{ env.STACK_NAME }}
          parameters: |
            [
              {
                "ParameterKey": "EcsImage",
                "ParameterValue": "${{ steps.docker.outputs.image }}"
              }
            ]
